name: Publish Homey App
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  main:
    name: Publish Homey App
    if: ${{ secrets.HOMEY_PAT != '' }}
    runs-on: ubuntu-latest
    concurrency:
      group: homey-publish-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v6

      - name: Publish Homey App
        uses: athombv/github-action-homey-app-publish@master
        id: publish
        with:
          personal_access_token: ${{ secrets.HOMEY_PAT }}

      - name: URL
        run: |
          echo "Manage your app at ${{ steps.publish.outputs.url }}." >> $GITHUB_STEP_SUMMARY
